project_id = "itjlzbnrdileuapsqwwe"
[functions.gerar-minuta]
enabled = true
verify_jwt = true
import_map = "./functions/gerar-minuta/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gerar-minuta/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gerar-minuta/*.html" ]

[functions.gemini]
enabled = true
verify_jwt = true
import_map = "./functions/gemini/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gemini/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gemini/*.html" ]
